# ============================================================
# mybash-win.ps1 — Automated Windows setup
# Run as: powershell -ExecutionPolicy Bypass -File mybash-win.ps1
# ============================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ============================================================
# Global variables
# ============================================================
$VIM_RUNTIME = "$env:USERPROFILE\.vim_runtime"
$FONT_DIR = "$env:LOCALAPPDATA\Microsoft\Windows\Fonts"
$WS_DIR = "$env:USERPROFILE\windows_scripts"

# ============================================================
# Helper: install via winget if not present
# ============================================================
function Install-IfMissing {
    param(
        [string]$Command,
        [string]$WingetId,
        [string]$Name
    )
    if (Get-Command $Command -ErrorAction SilentlyContinue) {
        Write-Host "  [OK] $Name already installed" -ForegroundColor Green
    } else {
        Write-Host "  [>>] Installing $Name..." -ForegroundColor Yellow
        winget install --id $WingetId --accept-source-agreements --accept-package-agreements -e
    }
}

# ============================================================
# Install packages via winget
# ============================================================
Write-Host "`n==> Installing packages..." -ForegroundColor Cyan

Install-IfMissing "git"       "Git.Git"                    "Git"
Install-IfMissing "vim"       "vim.vim"                    "Vim"
Install-IfMissing "rg"        "BurntSushi.ripgrep.MSVC"   "ripgrep"
Install-IfMissing "fzf"       "junegunn.fzf"              "fzf"
Install-IfMissing "fastfetch" "Fastfetch-cli.Fastfetch"   "Fastfetch"

# PowerShell 7
if (-not (Get-Command "pwsh" -ErrorAction SilentlyContinue)) {
    Write-Host "  [>>] Installing PowerShell 7..." -ForegroundColor Yellow
    winget install --id Microsoft.PowerShell --accept-source-agreements --accept-package-agreements -e
}

# Oh My Posh
if (-not (Get-Command "oh-my-posh" -ErrorAction SilentlyContinue)) {
    Write-Host "  [>>] Installing Oh My Posh..." -ForegroundColor Yellow
    winget install --id JanDeDobbeleer.OhMyPosh --accept-source-agreements --accept-package-agreements -e
}

# Refresh PATH
$env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")

# ============================================================
# Clone single-use files repository
# ============================================================
Write-Host "`n==> Cloning WS repository..." -ForegroundColor Cyan

if (Test-Path $WS_DIR) { Remove-Item -Recurse -Force $WS_DIR }
git clone https://github.com/hug0-f/windows_scripts.git $WS_DIR

# ============================================================
# Vim configuration
# ============================================================
Write-Host "`n==> Setting up Vim..." -ForegroundColor Cyan

if (Test-Path "$VIM_RUNTIME\.git") {
    git -C $VIM_RUNTIME fetch --all
} else {
    if (Test-Path $VIM_RUNTIME) { Remove-Item -Recurse -Force $VIM_RUNTIME }
    git clone --depth=1 https://github.com/amix/vimrc.git $VIM_RUNTIME
}

# Create _vimrc (Windows uses _ prefix)
$VIMRC = "$env:USERPROFILE\_vimrc"
@"
" DO NOT EDIT THIS FILE
set runtimepath+=~/.vim_runtime
source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry
"@ | Set-Content -Path $VIMRC -Encoding UTF8

# ============================================================
# Vim plugins cleanup & install
# ============================================================
Write-Host "`n==> Removing obsolete Vim plugins..." -ForegroundColor Cyan

$RemovePlugins = @(
    # Unused languages
    "vim-coffee-script", "vim-pug", "vim-bundle-mako", "vim-less", "vim-ruby",

    # Unused colorschemes (keeping dracula + gruvbox)
    "vim-pyte", "mayansmoke", "vim-colors-solarized",

    # Replaced by better plugins
    "vim-multiple-cursors",     # -> vim-visual-multi
    "ctrlp.vim",                # -> fzf.vim
    "ack.vim",                  # -> fzf + ripgrep
    "vim-flake8",               # -> ALE handles Python linting

    # Duplicates / rarely used
    "gist-vim", "vim-gist", "vim-yankstack"
)

foreach ($plugin in $RemovePlugins) {
    $target = "$VIM_RUNTIME\sources_non_forked\$plugin"
    if (Test-Path $target) {
        Remove-Item -Recurse -Force $target
        Write-Host "   Removed: $plugin" -ForegroundColor DarkGray
    }
}

Write-Host "`n==> Installing new Vim plugins..." -ForegroundColor Cyan

$NewPlugins = @{
    "fzf.vim"          = "https://github.com/junegunn/fzf.vim.git"
    "vim-visual-multi" = "https://github.com/mg979/vim-visual-multi.git"
    "vim-polyglot"     = "https://github.com/sheerun/vim-polyglot.git"
    "undotree"         = "https://github.com/mbbill/undotree.git"
    "vim-smoothie"     = "https://github.com/psliwka/vim-smoothie.git"
}

$MyPlugins = "$VIM_RUNTIME\my_plugins"
if (-not (Test-Path $MyPlugins)) { New-Item -ItemType Directory -Path $MyPlugins | Out-Null }

foreach ($name in $NewPlugins.Keys) {
    $url = $NewPlugins[$name]
    $target = "$MyPlugins\$name"

    if (Test-Path "$target\.git") {
        Write-Host "   Updating: $name" -ForegroundColor DarkGray
        git -C $target pull --quiet
    } else {
        Write-Host "   Installing: $name" -ForegroundColor DarkGray
        if (Test-Path $target) { Remove-Item -Recurse -Force $target }
        git clone --depth=1 $url $target
    }
}

# Persistent undo directory
$UndoDir = "$env:USERPROFILE\.cache\vim\undodir"
if (-not (Test-Path $UndoDir)) { New-Item -ItemType Directory -Path $UndoDir -Force | Out-Null }

# Copy personal vim config
if (Test-Path "$WS_DIR\my_configs.vim") {
    Copy-Item "$WS_DIR\my_configs.vim" "$VIM_RUNTIME\my_configs.vim" -Force
    Write-Host "   my_configs.vim copied" -ForegroundColor Green
}

# ============================================================
# Fonts (MesloLGS NF for Oh My Posh)
# ============================================================
Write-Host "`n==> Installing MesloLGS NF fonts..." -ForegroundColor Cyan

if (-not (Test-Path $FONT_DIR)) { New-Item -ItemType Directory -Path $FONT_DIR -Force | Out-Null }

$fonts = @("Regular", "Bold", "Italic", "Bold%20Italic")
$fontNames = @("Regular", "Bold", "Italic", "Bold Italic")

for ($i = 0; $i -lt $fonts.Count; $i++) {
    $url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20$($fonts[$i]).ttf"
    $dest = "$FONT_DIR\MesloLGS NF $($fontNames[$i]).ttf"

    if (-not (Test-Path $dest)) {
        Write-Host "   Downloading: MesloLGS NF $($fontNames[$i])" -ForegroundColor DarkGray
        Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
    }
}

# Register fonts
$ShellApp = New-Object -ComObject Shell.Application
$FontsFolder = $ShellApp.Namespace(0x14)
Get-ChildItem "$FONT_DIR\MesloLGS*.ttf" | ForEach-Object {
    $FontsFolder.CopyHere($_.FullName, 0x10)
}

# ============================================================
# fastfetch configuration
# ============================================================
Write-Host "`n==> Setting up fastfetch..." -ForegroundColor Cyan

$FFConfigDir = "$env:USERPROFILE\.config\fastfetch"
if (-not (Test-Path $FFConfigDir)) { New-Item -ItemType Directory -Path $FFConfigDir -Force | Out-Null }

if (Test-Path "$WS_DIR\fastfetch.config.jsonc") {
    Copy-Item "$WS_DIR\fastfetch.config.jsonc" "$FFConfigDir\config.jsonc" -Force
}

# ============================================================
# PowerShell profile
# ============================================================
Write-Host "`n==> Setting up PowerShell profile..." -ForegroundColor Cyan

# Ensure profile directory exists
$ProfileDir = Split-Path $PROFILE -Parent
if (-not (Test-Path $ProfileDir)) { New-Item -ItemType Directory -Path $ProfileDir -Force | Out-Null }

if (Test-Path "$WS_DIR\Microsoft.PowerShell_profile.ps1") {
    Copy-Item "$WS_DIR\Microsoft.PowerShell_profile.ps1" $PROFILE -Force
    Write-Host "   PowerShell profile copied" -ForegroundColor Green
}

# ============================================================
# Install PowerShell modules
# ============================================================
Write-Host "`n==> Installing PowerShell modules..." -ForegroundColor Cyan

$Modules = @("PSReadLine", "PSFzf", "Terminal-Icons")

foreach ($mod in $Modules) {
    if (-not (Get-Module -ListAvailable -Name $mod)) {
        Write-Host "   Installing: $mod" -ForegroundColor DarkGray
        Install-Module -Name $mod -Scope CurrentUser -Force -AllowClobber
    } else {
        Write-Host "   [OK] $mod already installed" -ForegroundColor Green
    }
}

# ============================================================
# Cleanup
# ============================================================
Write-Host "`n==> Cleaning up..." -ForegroundColor Cyan
if (Test-Path $WS_DIR) { Remove-Item -Recurse -Force $WS_DIR }

# ============================================================
# Done
# ============================================================
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  - Open Windows Terminal with PowerShell 7"
Write-Host "  - Set font to: MesloLGS NF"
Write-Host "  - Reboot recommended"
Write-Host ""
